import '../globals.css'

import { Analytics } from '@vercel/analytics/react'
import { Inter } from 'next/font/google'
import { notFound } from 'next/navigation'
import { NextIntlClientProvider } from 'next-intl'

import { NavBar } from '@/components/nav-bar'
import { ThemeProvider } from '@/components/theme-provider'
import { getMessages } from '@/lib/i18n/server'

import { FooterLinks } from './footer-links'

const inter = Inter({ subsets: ['latin'] })

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'zh-CN' }]
}

export const metadata = {
  title: 'Lemon Demo',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: LocaleType }
}) {
  let messages = {} as MessagesType
  try {
    messages = await getMessages(locale)
  } catch {
    notFound()
  }

  return (
    <html lang={locale}>
      <body
        className={`${inter.className} flex min-h-screen flex-col items-center bg-[#F7F1F1] p-8 dark:bg-[#333333]`}
      >
        <NextIntlClientProvider locale={locale} messages={messages.Index}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header>
              <NavBar labels={messages.Nav} />
            </header>
            <main className="w-full max-w-3xl flex-1 py-8">{children}</main>
            <footer className="w-full max-w-3xl font-semibold">
              <FooterLinks />
            </footer>
          </ThemeProvider>
        </NextIntlClientProvider>
        <Analytics />
      </body>
    </html>
  )
}
