import './globals.css'

import { Inter } from 'next/font/google'
import { notFound } from 'next/navigation'

import { NavBar } from '@/components/nav-bar'
import { ThemeProvider } from '@/components/theme-provider'
import { getMessages } from '@/lib/i18n/server'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Lemon Demo',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: RootParams
}) {
  try {
    await getMessages(params)
  } catch {
    notFound()
  }

  return (
    <html lang={params.locale}>
      <body
        className={`${inter.className} flex min-h-screen flex-col items-center bg-[#F7F1F1] p-8 dark:bg-[#333333]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="flex justify-center">
            <NavBar />
          </header>
          <main className="w-full max-w-3xl flex-1 py-8">{children}</main>
          <footer className="font-semibold">Power by vercel&Next.js</footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
